from typing import Optional
from pydantic import Field
from bcsync.api.schemas.base import BCEntityModel


class Item(BCEntityModel):
    code: str = Field(alias='no')
    name: Optional[str] = Field(alias='description')
    name_2: Optional[str] = Field(alias='description2')
    bar_code: Optional[str] = Field(alias='gtin')
    item_type: Optional[str] = Field(alias='type')
    item_category_code: Optional[str] = Field(alias='itemCategoryCode')
    inventory_posting_group_code: Optional[str] = Field(alias='inventoryPostingGroup')
    country_of_origin_code: Optional[str] = Field(alias='countryOfOriginCode')
    base_unit_of_measure_code: Optional[str] = Field(alias='baseUnitOfMeasure')
    dimension_1_code: Optional[str] = Field(default=None, alias='globalDimension1Code')
    dimension_2_code: Optional[str] = Field(default=None, alias='globalDimension2Code')
    unit_price: float = Field(alias='unitPrice')
    unit_cost: float = Field(alias='unitCost')
    standard_cost: float = Field(alias='standardCost')
    unit_list_price: float = Field(alias='unitListPrice')
    profit_percentage: float = Field(alias='profitPercentage')
    price_includes_vat: bool = Field(alias='priceIncludesVAT')
    costing_method: Optional[str] = Field(alias='costingMethod')
    price_profit_calculation: Optional[str] = Field(alias='priceProfitCalculation')
    gross_weight: float = Field(alias='grossWeight')
    net_weight: float = Field(alias='netWeight')
    safety_stock_quantity: float = Field(alias='safetyStockQuantity')
    assembly_policy: Optional[str] = Field(alias='assemblyPolicy')
    manufacturing_policy: Optional[str] = Field(alias='manufacturingPolicy')
    stockout_warning: Optional[str] = Field(alias='stockoutWarning')
    reserve: Optional[str] = Field(alias='reserve')
    blocked: bool = Field(alias='blocked')
    sales_blocked: bool = Field(alias='salesBlocked')
    purchasing_blocked: bool = Field(alias='purchasingBlocked')
    service_blocked: bool = Field(alias='serviceBlocked')
    critical: bool = Field(alias='critical')
